SU-SOE/engineering_profile

config/sync/colorbox.settings.yml, config/sync/core.entity_view_display.paragraph.stanford_media_caption.default.yml, config/sync/core.extension.yml, config/sync/editor.editor.stanford_html.yml, config/sync/field.field.media.stanford_gallery_images.su_gallery_image.yml, config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml, config/sync/filter.format.stanford_html.yml, config/sync/mathjax.settings.yml, config/sync/views.view.stanford_person.yml, config/sync/views.view.stanford_person_list_terms_first.yml, config/sync/views.view.stanford_publications.yml, tests/codeception/acceptance/Content/BasicPageCest.php, tests/codeception/functional/Paragraphs/GalleryCest.php
- Upstream changes from soe_profile as of 7/9/2021
4. Verify...
- Other PRs
- Anyone who should be notified? (`@mention` them …
=> Corrected the events schedule display settings for the pattern refactor

tests/codeception/acceptance/Content/PersonCest.php
=> test fixup

config/sync/migrate_plus.migration.soe_people_spotlight_d7_images.yml, config/sync/migrate_plus.migration.soe_people_spotlight_d7_media.yml, config/sync/migrate_plus.migration.soe_people_spotlight_d7_node.yml, config/sync/migrate_plus.migration.soe_people_spotlight_d7_paragraphs.yml, config/sync/migrate_plus.migration.soe_stanford_pages_d7_paragraph_rows.yml
=> SOED9-118 - spotlight migration yamls 

config/sync/core.base_field_override.node.spotlight.title.yml, config/sync/core.entity_form_display.node.spotlight.default.yml, config/sync/core.entity_view_display.node.spotlight.default.yml, config/sync/core.entity_view_display.node.spotlight.teaser.yml, config/sync/field.field.node.spotlight.body.yml, config/sync/field.field.node.spotlight.su_soe_department.yml, config/sync/field.field.node.spotlight.su_spotlight_affiliation.yml, config/sync/field.field.node.spotlight.su_spotlight_degrees.yml, config/sync/field.field.node.spotlight.su_spotlight_feature_image.yml, config/sync/field.field.node.spotlight.su_spotlight_person_title.yml, config/sync/field.field.node.spotlight.su_spotlight_quote.yml, config/sync/field.storage.node.su_spotlight_affiliation.yml, config/sync/field.storage.node.su_spotlight_degrees.yml, config/sync/field.storage.node.su_spotlight_feature_image.yml, config/sync/field.storage.node.su_spotlight_person_title.yml, config/sync/field.storage.node.su_spotlight_quote.yml, config/sync/node.type.spotlight.yml, config/sync/rabbit_hole.behavior_settings.node_type_spotlight.yml, config/sync/taxonomy.vocabulary.affiliation.yml, modules/custom/engineering_profile_helper/content/taxonomy_term/238736c6-516b-4092-835d-b61b4da8b14e.yml, modules/custom/engineering_profile_helper/content/taxonomy_term/27ce72b5-b9a3-4554-9a18-a1c6cae2f904.yml, modules/custom/engineering_profile_helper/content/taxonomy_term/730b3511-5e34-4257-b2da-cdf3afeba625.yml, modules/custom/engineering_profile_helper/content/taxonomy_term/7ed3e65f-e2db-419b-88c7-8a14cba063dc.yml, modules/custom/engineering_profile_helper/content/taxonomy_term/7ff7a24b-2afc-4e8d-bd65-9c051261af33.yml, modules/custom/engineering_profile_helper/content/taxonomy_term/a9fdf582-b3ac-4c05-8d40-f6113c60f082.yml, tests/codeception/acceptance/Content/EngineeringVocabulariesCest.php
- Configs for Spotlight CT fields.
- configs for Affiliations vocab
- default content for Affiliations vocab
- tests for Affiliations default content
- ASAP
- Medium
- Normal
2. `blt drupal:update`
3. navigate to `/node/add/spotlight`.  verify you can add a node.
4. navigate to `/admin/structure/taxonomy/manage/affiliation/overview`.  Verify you can see the default terms there, and they match https://engineering.stanford.edu/admin/structure/taxonomy/stanford_affiliation
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality …
=> added field configs

config/sync/migrate_plus.migration.magazine_items_d7_images.yml, config/sync/migrate_plus.migration.magazine_items_d7_media.yml, config/sync/migrate_plus.migration.magazine_items_d7_node.yml, config/sync/migrate_plus.migration.magazine_items_paragraphs_d7.yml, config/sync/migrate_plus.migration_group.magazine_items_d7.yml
- Migrations for magazine article content
- asap
- higher than average
- higher than average
2. `drush cim && drush cr`
3. navigate to: `/admin/structure/migrate/manage/magazine_items_d7/migrations`
4. run the SOE Magazine Nodes migration.
5. verify the content imports correctly.
- Is there a config:export in this PR that changes the config sync directory? YES
- Other PRs
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test …
=> Magazine migrations

CHANGELOG.md, config/sync/mathjax.settings.yml, engineering_profile.info.yml, tests/codeception/functional/Contrib/ExtLinkCest.php
=> D8CORE-2594 Allow menu placement under unpublished pages (#435)

config/sync/migrate_plus.migration.soe_people_spotlight_d7_node.yml
- ASAP
- High
- High
4. Verify...
- Other PRs
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML …
=> FIXUP! - added format for Spotlight Story.

config/sync/migrate_plus.migration.soe_people_spotlight_d7_node.yml
=> FIXUP! - added pathauto and path alias processes.

config/sync/migrate_plus.migration.magazine_items_d7_images.yml, config/sync/migrate_plus.migration.magazine_items_d7_media.yml, config/sync/migrate_plus.migration.magazine_items_d7_node.yml, config/sync/migrate_plus.migration.magazine_items_paragraphs_d7.yml
- Fixup - points to dev site endpoints rather than production's. 
- ASAP
- HIgh
=> FIXUP: point to engineering XML feed instead of prod.

config/sync/migrate_plus.migration.magazine_items_d7_node.yml, config/sync/migrate_plus.migration.soe_people_spotlight_d7_node.yml
- added a trim callback for taxonomy term creation in the magazine migration
- asap
4. Verify...
- Other PRs
- …
=> Added a trim for taxonomy terms to prevent duplicates

themes/engineering/engineering.theme
- If there's no "more" link, an exception is thrown. This fixes that.
- ASAP
- high
2. start without any spotlight content.
3. create a Spotlight.
4. load the page, confirm no error is thrown.
- Other PRs
- [AMP …
=> Added a check to make sure the "more" link exists before modifying it.

themes/engineering/dist/js/engineering.script.js, themes/engineering/lib/js/engineering.js
- Re-added import from that was present in final version of SOED9-17 branch didn't make it to 8.x: https://github.com/SU-SOE/engineering_profile/pull/40/files
- ASAP
=> FIXUP (SOED9-17) added import that somehow got lost in the merge.

config/sync/views.view.magazine_article_collection.yml, themes/engineering/dist/css/engineering.components.css, themes/engineering/dist/css/engineering.styles.css, themes/engineering/dist/css/print.styles.css, themes/engineering/dist/js/engineering.script.js, themes/engineering/lib/js/engineering.js, themes/engineering/lib/scss/page/article_collection/article_collection.scss, themes/engineering/package-lock.json, themes/engineering/webpack.config.js
- The corrects some problems with the views and the styles for article collections that were causing problems with HTML validation.
- asap
- high
- high
2. `drush cim; drush cr`
3. visit `/taxonomy/term/296` and verify it looks alright.
- Is there a config:export in this PR that changes the config sync directory? YES
- Other PRs
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCj …
=> Article collection fixup

config/sync/metatag.metatag_defaults.global.yml
=> FIXUP - disabled metatag's nofollow, noindex

config/sync/pathauto.pattern.spotlight_nodes.yml
=> Adding alias for spotlight nodes.

config/sync/core.entity_view_display.node.stanford_news.default.yml, config/sync/core.entity_view_display.taxonomy_term.department.default.yml, config/sync/views.view.department_terms.yml, themes/engineering/dist/css/engineering.components.css, themes/engineering/dist/css/engineering.styles.css, themes/engineering/dist/css/print.styles.css, themes/engineering/dist/js/engineering.script.js, themes/engineering/lib/scss/components/department-terms/_department_terms.scss, themes/engineering/lib/scss/components/department-terms/index.scss, themes/engineering/lib/scss/components/index.scss
- This adds the related department block onto news/magazine pages.
- This also adds landing pages for department terms.
- asap
- it's a yellow on the punch list.
- high
1. Checkout branch.
2. `drush cim`
3. Clear caches.
4. visit a magazine story.  Ensure there is a block at the bottom that lists related departments.
5. The landing page won't look right until the magazine-fixup branch is merged.
- Other PRs
- [AMP …
=> Added related departments to the magazine news stories

themes/engineering/dist/js/engineering.script.js, themes/engineering/lib/js/engineering.behavior.js
- The AJAX call and a jquery clone was creating ghost buttons with the same ID. This should prevent this
- ASAP
- 2
- lowish
2. Rebuild Cache and import config `blt drupal:update`
3. Navigate to /spotlight
4. Click the "load more" button at least more than twice.
5. Inspect the apply button. You should see two buttons, one hidden and visible. 
- Other PRs
- [AMP …
=> Fixup: fixed ghost button creation.

config/sync/metatag.metatag_defaults.global.yml
=> FIXUP - turn off metatag nobot

composer.json
=> back to dev

composer.json, config/sync/core.entity_form_display.node.spotlight.default.yml, config/sync/core.entity_form_display.taxonomy_term.article_collection.default.yml, config/sync/core.entity_form_display.taxonomy_term.magazine_issues.default.yml, config/sync/metatag.metatag_defaults.node.yml
=> config updates for metatag
